#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@PikpakDrive-fuse[-1]
	add ucitrack PikpakDrive-fuse
	set ucitrack.@PikpakDrive-fuse[-1].init=PikpakDrive-fuse
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
