#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@Pikpak-fuse[-1]
	add ucitrack Pikpak-fuse
	set ucitrack.@Pikpak-fuse[-1].init=Pikpak-fuse
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
