#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pikpak-fuse[-1]
	add ucitrack pikpak-fuse
	set ucitrack.@pikpak-fuse[-1].init=pikpak-fuse
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
