include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-Pikpak-fuse
PKG_VERSION:=0.1.12
PKG_RELEASE:=1
PKG_PO_VERSION:=$(PKG_VERSION)-$(PKG_RELEASE)

PKG_LICENSE:=MIT
PKG_MAINTAINER:=ykxVK8yL5L <https://github.com/ykxVK8yL5L>

LUCI_TITLE:=LuCI Support for Pikpak-fuse
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+Pikpak-fuse

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
