include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-pikpak-fuse
PKG_VERSION:=0.1.13
PKG_RELEASE:=1
PKG_PO_VERSION:=$(PKG_VERSION)-$(PKG_RELEASE)

PKG_LICENSE:=MIT
PKG_MAINTAINER:=ykxVK8yL5L <https://github.com/ykxVK8yL5L>

LUCI_TITLE:=LuCI Support for pikpak-fuse
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+pikpak-fuse

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
