name: Release for Openwrt
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.1.14'

jobs:
  openwrt:
    name: OpenWrt Package - ${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    # needs: [ linux ]
    environment: OpenWrt
    strategy:
      matrix:
        target:
          - arch: "aarch64_generic"
            sdk: "https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/openwrt-sdk-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
          - arch: "arm_cortex-a9"
            sdk: "https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic/openwrt-sdk-bcm53xx-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz"
          - arch: "aarch64_cortex-a53"
            sdk: "https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2710/openwrt-sdk-bcm27xx-bcm2710_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
          - arch: "aarch64_cortex-a72"
            sdk: "https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2711/openwrt-sdk-bcm27xx-bcm2711_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
          - arch: "x86_64"
            sdk: "https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
          - arch: "i386_pentium4"
            sdk: "https://downloads.openwrt.org/snapshots/targets/x86/generic/openwrt-sdk-x86-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
          - arch: "arm_cortex-a7_neon-vfpv4"
            sdk: "https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/openwrt-sdk-ipq40xx-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz"
    steps:
      - uses: actions/checkout@v2
      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
          python3-distutils python3-setuptools python3-dev rsync subversion \
          swig time xsltproc zlib1g-dev
      - name: Install OpenWrt SDK
        run: |
          wget -O openwrt-sdk.tar.xz ${{ matrix.target.sdk }}
          xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
          mv -f openwrt-sdk-* openwrt-sdk
      - name: Build Package
        run: |
          echo "src-link pikpakDrive $GITHUB_WORKSPACE/openwrt" > openwrt-sdk/feeds.conf
          echo 'CONFIG_PACKAGE_pikpak-fuse=y
          CONFIG_PACKAGE_luci-app-pikpak-fuse=y
          ' >> openwrt-sdk/.config
          cd openwrt-sdk
          cat feeds.conf.default >> feeds.conf
          cat feeds.conf
          ./scripts/feeds update -a > /dev/null
          make defconfig
          ./scripts/feeds install -d y -p "pikpakDrive" -f -a
          make package/pikpak-fuse/compile V=s
          make package/luci-app-pikpak-fuse/compile V=s
          tree bin/packages/
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: pikpak-fuse-openwrt-${{ matrix.target.arch }}
          path: openwrt-sdk/bin/packages/*/pikpakDrive/pikpak-fuse*.ipk
          if-no-files-found: error
      - name: Archive luci packages
        uses: actions/upload-artifact@v2
        if: ${{ matrix.target.arch == 'aarch64_generic' }}
        with:
          name: pikpak-fuse-openwrt-${{ matrix.target.arch }}
          path: openwrt-sdk/bin/packages/*/pikpakDrive/luci-*.ipk
          if-no-files-found: error
      - name: Upload package to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: openwrt-sdk/bin/packages/*/pikpakDrive/pikpak-fuse*.ipk
          tag: "refs/tags/${{ github.event.inputs.tag }}"
      - name: Upload luci packages to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: openwrt-sdk/bin/packages/*/pikpakDrive/luci-*.ipk
          tag: "refs/tags/${{ github.event.inputs.tag }}"

  